### ISSUE TITLE
Class 6. （後半） Exercise 1. log

### ISSUE THREAD

**Issue by yashinomi** [yashinomi/sysdev2020_advanced#30]
CircleCIをつかったossを探そう

**Comment by yashinomi** [comment]
`github .circleci/config.yml`で[検索](https://www.google.com/search?client=safari&rls=en&sxsrf=ALeKk0145dfEFYkTmIEi1T0r9MVZzR0T9w%3A1605252516162&ei=pDWuX7O_CcebmAXKxIS4Dg&q=github+.circleci%2Fconfig.yml&oq=github+.circleci%2Fconfig.yml&gs_lcp=CgZwc3ktYWIQAzIGCAAQCBAeOgQIIxAnOgQIABAeUKYcWK06YJQ8aABwAHgAgAGEAYgBwwqSAQQyLjEwmAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=psy-ab&ved=0ahUKEwizoYDQ__7sAhXHDaYKHUoiAecQ4dUDCAw&uact=5)。
circleci のドキュメントばかり出る

**Comment by yashinomi** [comment]
`site:github.com .circleci/config.yml`で[検索](https://www.google.com/search?client=safari&rls=en&sxsrf=ALeKk03TIbc9GKARhA6vJEwWwNPqNisPGQ%3A1605252524575&ei=rDWuX6bbIpKkmAXvn5_QDg&q=site%3Agithub.com+.circleci%2Fconfig.yml&oq=site%3Agithub.com+.circleci%2Fconfig.yml&gs_lcp=CgZwc3ktYWIQAzoECCMQJzoGCAAQCBAeOgcIIxCwAhAnOggIABAIEA0QHjoFCAAQzQJQosoHWOPpB2Ci6wdoAXAAeACAAXuIAfEIkgEDNS42mAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=psy-ab&ved=0ahUKEwim4YHU__7sAhUSEqYKHe_PB-oQ4dUDCAw&uact=5)。
いくつかヒット。

**Comment by yashinomi** [comment]
optunaというossを例にとりあげる。
[https://github.com/optuna/optuna/blob/master/.circleci/config.yml](https://github.com/optuna/optuna/blob/master/.circleci/config.yml)

**Comment by yashinomi** [comment]
複数のdockerイメージを使っていた。
いくつか例示する。
- circleci/python:3.7 
- circleci/redis:5.0.7

**Comment by yashinomi** [comment]
案の定様々なテストを実行している。
pythonによるテストを抜粋する。
```
 - run: &tests
          name: tests
          command: |
            . venv/bin/activate
            pytest --cov=optuna tests
          environment:
            OMP_NUM_THREADS: 1
```
